### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by thomastthai** [smukov/AvI#39]
Thank you for porting this to Ionic 2. Has anyone port it to work on the web using Angular 2?

**Comment by smukov** [comment]
Hi @thomastthai , I don't have any plans to use this project as a PWA (Progressive Web App) atm, if that's what you mean.

**Comment by thomastthai** [comment]
Thanks. It worked well with Ionic 2.

**Comment by thomastthai** [comment]
Btw, one thing I noticed was if the avatar picture isn't square, it will
display it squeezed in eiher horizontally or vertically.
